version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - make -C docs/ regenerate
    build:
      html:
        - make -C docs/ html

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      # extra_requirements:
      #   - mcp
      #   - openapi
      #   - langchain
sphinx:
  configuration: docs/source/conf.py
